### ISSUE TITLE
how does llvm-pretty compare with llvm-hs or llvm-general?

### ISSUE THREAD

**Issue by minad** [GaloisInc/llvm-pretty#10]

**Comment by elliottt** [comment]
I think that the major difference is that it's explicitly not using the llvm library. Originally, its purpose was to provide an easy way of producing textual llvm source, via an EDSL for constructing an AST, and a pretty printer for that AST. It's scope has increased a bit since then, and there's now a [parser](https://github.com/galoisinc/llvm-pretty-bc-parser) for the bitcode format that's maintained separately.
