### ISSUE TITLE
Support opaque pointers

### ISSUE THREAD

**Issue by langston-barrett** [GaloisInc/llvm-pretty#102]
LLVM is in the process of migrating all of its pointer types from `i8*`, `i32*`, etc. to an opaque `ptr` type, as described [here](https://llvm.org/docs/OpaquePointers.html). LLVM 13 takes an important step in that direction, as it is the first LLVM release to include `ptr` in the LLVM AST. See https://github.com/llvm/llvm-project/commit/2155dc51d700c9fb5f29d79eaacf5e1470e4d8ca.

We should support opaque pointers in the LLVM AST and pretty-printer. In particular, we will have to either add a new `OpaquePointer` constructor that doesn't take a pointee type as an argument, or make [`PtrTo`](https://github.com/elliottt/llvm-pretty/blob/31612ff381fba3971263371daab452faab5b76fe/src/Text/LLVM/AST.hs#L262) take a `Maybe`.

See also: https://github.com/GaloisInc/llvm-pretty-bc-parser/issues/177

**Comment by RyanGlScott** [comment]
Hah, I just learned that LLVM also has an [`opaque`](https://releases.llvm.org/15.0.0/docs/LangRef.html#opaque-structure-types) structure type that is completely unrelated to opaque pointers (just in case you thought there weren't enough concepts with "opaque" in the name), which `llvm-pretty` represents as [`Opaque`](https://github.com/elliottt/llvm-pretty/blob/31612ff381fba3971263371daab452faab5b76fe/src/Text/LLVM/AST.hs#L266). I wonder if it would be confusing to have both `Opaque` and `OpaquePointer`.

**Comment by RyanGlScott** [comment]
To echo similar sentiments as in https://github.com/GaloisInc/llvm-pretty-bc-parser/issues/177#issuecomment-1476070897, I've discovered that adding support the opaque `ptr` type in `llvm-pretty` itself is actually quite straightforward. The tricky part is making sure that instructions which _use_ opaque pointers behave as expected.

In particular, I've recently discovered that the way that `llvm-pretty-bc-parser` treats `call` and `callbr` instructions is subtly broken, and I only realized this when trying to make them work with opaque pointers. See https://github.com/GaloisInc/llvm-pretty-bc-parser/issues/189#issuecomment-1476068137 for the full story, but the tl;dr version is that `call` is using a pointer type in a place where it should actually be using a function type. We didn't notice this problem when using pointers with explicit pointee types, but once we switch over to opaque pointers, we will no longer be able to "look through" pointer types.

This convention of using a pointer type instead of a function type in `call` instructions can also be found in `llvm-pretty`:

https://github.com/elliottt/llvm-pretty/blob/a272e380bbd44d6af5afba63a70772b2dab6a2d0/src/Text/LLVM/PP.hs#L695-L697

I will need to adjust this code as well. I'll open a patch for this.

There may be more instructions that need similar adjustments, but I haven't done a thorough audit of all pointer-aware instructions yet.

**Comment by RyanGlScott** [comment]
I did a slightly more thorough audit of `Text.LLVM.PP`, and I found three opaque pointer "violations" that we will need to address:

* The pretty-printer for `callbr` instructions inspects the pointee type of the value it is invoking:

  https://github.com/elliottt/llvm-pretty/blob/b13493fda7276835a4e19bf13a9fb1b3e08083a9/src/Text/LLVM/PP.hs#L682-L694

  This wouldn't work if the type of the value is an opaque `ptr`. Luckily, we already store the return type as a standalone `Type` field in `CallBr`, so fixing this should simply be a matter of removing `res` in favor of `ty`.
* The pretty-printer for `load` instructions inspects the pointee type of the pointer it is loading from:

  https://github.com/elliottt/llvm-pretty/blob/b13493fda7276835a4e19bf13a9fb1b3e08083a9/src/Text/LLVM/PP.hs#L618-L621

  This one is a bit trickier, as we do not store the load type as a separate field in `Load`. I think we will need to change the definition of `Load` to do so.
* The pretty-printer for `getelementptr` instructions inspects the pointee type of the pointer it is calculating the address of:

  https://github.com/elliottt/llvm-pretty/blob/b13493fda7276835a4e19bf13a9fb1b3e08083a9/src/Text/LLVM/PP.hs#L728-L731

  Like with `Load`, I think we will need to tweak the definition of `GEP` to store this `Type` separately. We should do something similar for `ConstGEP`.
* The code in `resolveGep` looks inspects pointee types:

  https://github.com/elliottt/llvm-pretty/blob/b13493fda7276835a4e19bf13a9fb1b3e08083a9/src/Text/LLVM/AST.hs#L1429-L1432

**Comment by RyanGlScott** [comment]
Another issue that I ran into in https://github.com/GaloisInc/llvm-pretty-bc-parser/issues/177#issuecomment-1497512507 was needing to compare types modulo pointer opaqueness. This is because many parts of `llvm-pretty` and its surrounding ecosystem still use `PtrTo` (and will likely do so for the foreseeable future), and as a result, there are often cases where you have a type equality between a `PtrTo` and a `PtrOpaque`. For this reason, I ended up implementing the following functions to make `llvm-pretty-bc-parser` work with opaque pointers:

```hs
eqTypeModuloOpaquePtrs :: Eq ident => Type' ident -> Type' ident -> Bool
cmpTypeModuloOpaquePtrs :: Ord ident => Type' ident -> Type' ident -> Ordering
```

There's nothing parser-specific about these functions, however, so I wonder if we should put these in `llvm-pretty`.

-----

Another challenge is that LLVM itself does not allow mixing opaque and non-opaque pointers in a single file, so if you try to use `Text.LLVM.AST` to pretty-print such a file, then `llvm-as` will reject it. I wrote another utility function that checks if a file contains at least one opaque pointer, and if so, replaces all non-opaque pointers with opaque ones to make is `llvm-as`–compliant:

```hs
fixupOpaquePtrs :: forall a. Data a => a -> a
```

Perhaps this is something that `llvm-pretty`'s pretty-printer should always do. On the other hand, it requires an extra traversal of the entire AST using `syb`, so this has potential performance implications. Perhaps we should not do this by default, but offer the function to those who want to use it?
