### ISSUE TITLE
Pretty-printing of infinite floating point and NaNs is incorrect/lossy

### ISSUE THREAD

**Issue by Ptival** [GaloisInc/llvm-pretty#135]
Specifically, this line is giving me trouble:

https://github.com/elliottt/llvm-pretty/blob/c4411152b05a59f0a4d6013c7f51178ab7368d81/src/Text/LLVM/PP.hs#L817

This uses [pretty's `double`](https://hackage.haskell.org/package/pretty-1.1.3.6/docs/src/Text.PrettyPrint.HughesPJ.html#double) which calls the [`show` instance for `Double`](https://hackage.haskell.org/package/base-4.19.1.0/docs/src/GHC.Float.html#formatRealFloatAlt), and for any `NaN` or `+/- Infinity`, it will print literally these strings.

This creates invalid LLVM IR, e.g.:
```
  %13 = fcmp oeq double %12, Infinity
```
which is not accepted by clang.

`llvm-dis` would instead create:
```
  %13 = fcmp oeq double %12, 0x7FF0000000000000
```
which recompiles correctly.

---

We could special case for `Nan`/`Infinity` the way the `show` instance does, and instead choose to grab the hexadecimal representation of the given choice of `Nan`/`Infinity` by doing:
```
text "0x" <> text (showHex (castDoubleToWord64 i) "")
```

But I almost wonder whether we just want to use this for all floats and doubles (even the representable ones).

Thoughts? @elliottt @RyanGlScott @kquick

**Comment by Ptival** [comment]
To make things more concrete, I'm asking whether we're wanting to go as far as:

```haskell
  -- Note: we favor outputting the hexadecimal representation here because it also naturally
  -- supports the printing of the bit-correct values for Inf/-Inf/NaNs.
  ValFloat i         -> text "0x" <> text (showHex (castFloatToWord32 i) "")
  ValDouble i        -> text "0x" <> text (showHex (castDoubleToWord64 i) "")
```

or whether we want to still use `float`/`double` (and thus `show`) when dealing with representable numbers.

**Comment by RyanGlScott** [comment]
Personally, I would be OK with only using hexadecimal notation for infinite and NaN values. This is the same convention that LLVM uses when displaying floating-point constants (see [the LLVM language reference](https://llvm.org/docs/LangRef.html#simple-constants)).

**Comment by kquick** [comment]
Same here.  There are a number of ways that the values could be shown, and the hex format seems the most robust.  Since LLVM accepts that format, I'd vote for that.

**Comment by Ptival** [comment]
I pushed a proposal for a fix matching LLVM.

**Comment by tomsmeding** [comment]
Unfortunately, the printing introduced by https://github.com/GaloisInc/llvm-pretty/commit/64c4808381464a51d833c17ca4ffa35d1bcb2e33 is not quite valid for LLVM. As can be seen in [the reference documentation](https://llvm.org/docs/LangRef.html#simple-constants), LLVM expects a `double`-sized hex value even for `float`-typed constants.

This is also true in practice: the snippet
```llvm
define void @testfun() {
  %a = fadd float 1.0, 0xffc00000
  ret void
}
```
(`0xffc00000` is a regular `NaN`) yields the following output when passed to `opt -S`:
```
opt: <stdin>:2:24: error: floating point constant invalid for type
  %a = fadd float 1.0, 0xffc00000
                       ^
```
The same error is produced for LLVM 12, 15 and 18 (this is what I have lying around).

On the other hand, the following:
```llvm
define void @testfun() {
  %a = fadd float 1.0, 0xfff8000000000000
  ret void
}
```
(`0xfff8000000000000` is a regular `NaN` for `double`) is accepted.

The documentation further states that even though constants must be specified as IEEE double-precision values, they must be losslessly convertable to `float` in order to be accepted as constants of type `float`. For NaNs (which have a bunch of freely choosable bits), this apparently means that of the 52 mantissa bits in a `double`, only the first 23 (the number of mantissa bits in a `float`) may be nonzero. Indeed, in the following snippet:
```llvm
define void @testfun() {
  %a = fadd float 1.0, 0xfff80011e0000000
  %b = fadd float 1.0, 0xfff80011f0000000
  ret void
}
```
the assignment to `%a` is accepted, but `%b` is not because the low-order bit of that `f` exceeds the space in a `float` mantissa.

As an aside: LLVM seems to do this check based on the length of the literal itself. Indeed, of course, `0x1` is also a valid 64-bit value, but LLVM really wants `0x0000000000000001` if it is used as a constant of type `float`. For `double`, however, there is no such check: LLVM simply reads the hexadecimal literal as a number. Indeed, the following snippet:
```llvm
define i32 @testfun() {
  %d1 = fadd double 1.0, 0xffc00000
  %d2 = fadd double 1.0, 0x00000000ffc00000
  %d1i64 = bitcast double %d1 to i64
  %d2i64 = bitcast double %d2 to i64
  %eq = icmp eq i64 %d1i64, %d2i64
  %ret = zext i1 %eq to i32
  ret i32 %ret
}
```
optimises to `ret i32 1` on the `-O1` optimisation level.

**Comment by Ptival** [comment]
@tomsmeding I have a tentative fix [here](https://github.com/GaloisInc/llvm-pretty/pull/137).

If there is a concrete use case where you could test it and give feedback, please let us know.

I think I'm doing the correct thing (essentially 1-extending the exponent field and 0-right-extending the mantissa), but it'd be good to know that this works in practice.
